### ISSUE TITLE
Device callbacks do not need to by Sync

### ISSUE THREAD

**Issue by sdonnan** [ExPixel/miniaudio-rs#20]
Currently the device callbacks require the `Sync` trait, but since the callback is cloned for each thread I believe this is unnecessary. `Send` and `Clone` seem sufficient.

The `Sync` trait makes it difficult to implement a pattern where, for example, one might use an `mpsc::Sender` to emit events from the callback.

**Comment by ExPixel** [comment]
Merged your PR, thanks.
