### ISSUE TITLE
miniaudio::Error doesn't implement std::error::Error - is this on purpose?

### ISSUE THREAD

**Issue by ohmree** [ExPixel/miniaudio-rs#49]
Currently `miniaudio::Error` doesn't implement `std::error::Error`.  
This makes it hard to work with crates like [anyhow](https://github.com/dtolnay/anyhow) and its fork [eyre](https://github.com/yaahc/eyre). Instead of a single question mark operator that bubbles up the error I need to either use `expect` which only works the same inside `main`, find the right combination of `map_err` and `eyre!`/`anyhow!` (which is verbose and not very DRY) or manually handle errors with `if let`/`match` + `return` which is arguably worse.

Is there any particular reason for this? If not I think I could try whipping up a PR sometime soon, potentially using [thiserror](https://github.com/dtolnay/thiserror) if it works well with the integer-based error representation miniaudio uses.

**Comment by ExPixel** [comment]
No. It's an oversight on my part for sure. The miniaudio API is looking like it's stabilizing so it's probably time to start making changes again, though.
